//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFrontLab.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public short ProductID { get; set; }
        public short ProductTypeID { get; set; }
        public short ManufacturerID { get; set; }
        public Nullable<int> UnitsSold { get; set; }
        public Nullable<bool> InStock { get; set; }
        public string ProductImage { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ProductName { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
